"""Deterministic indexes, publication views and template rendering."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .errors import BuildMismatchError, KnowledgeError
from .graph import collect_backlinks
from .markdown import extract_section_to_eof
from .repository import KnowledgeRepository


GENERATED_COMMENT = "<!-- Generated by repository tooling. Do not edit directly. -->"
PUBLICATION_PATTERN = re.compile(r'\{\{\s*publication\s+"([^"]+)"\s*\}\}')
INCLUDE_TOPIC_PATTERN = re.compile(
    r'^\s*\{\{\s*include-topic\s+"([a-z0-9-]+)"\s+section="([^"]+)"\s*\}\}\s*$'
)
UNRESOLVED_PATTERN = re.compile(r"\{\{.*?\}\}", re.DOTALL)


@dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: str
    repository_root: Path | None = None


def _string(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _table_cell(value: object) -> str:
    """Render one stable, single-line Markdown table cell."""

    collapsed = re.sub(r"\s+", " ", _string(value)).strip()
    return collapsed.replace("|", r"\|")


def _link(label: str, target: str) -> str:
    return f"[{label}]({target})"


def _header(title: str, command: str) -> list[str]:
    return [GENERATED_COMMENT, "", f"# {title}", "", f"Generated by `{command}` from canonical repository data.", ""]


def generate_knowledge_index(repository: KnowledgeRepository) -> str:
    lines = _header("Knowledge Index", "KnowledgeSystem/Tools/build-index")
    lines.extend(
        [
            "| ID | Title | Topic | Kind | State | Maturity |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for document in sorted(repository.knowledge, key=lambda item: str(item.metadata.get("id", ""))):
        metadata = document.metadata
        identifier = _string(metadata.get("id"))
        lines.append(
            "| "
            + " | ".join(
                [
                    _link(identifier, f"items/{document.path.name}"),
                    _table_cell(metadata.get("title")),
                    _table_cell(metadata.get("topic")),
                    _table_cell(metadata.get("kind")),
                    _table_cell(metadata.get("state")),
                    _table_cell(metadata.get("maturity")),
                ]
            )
            + " |"
        )
    if not repository.knowledge:
        lines.append("| — | No Knowledge Objects | — | — | — | — |")
    return "\n".join(lines).rstrip() + "\n"


def generate_decision_index(repository: KnowledgeRepository) -> str:
    lines = _header("Decision Index", "KnowledgeSystem/Tools/build-index")
    lines.extend(["| ID | Title | Status | Date | Scope |", "| --- | --- | --- | --- | --- |"])
    for document in sorted(repository.decisions, key=lambda item: str(item.metadata.get("id", ""))):
        metadata = document.metadata
        identifier = _string(metadata.get("id"))
        lines.append(
            "| "
            + " | ".join(
                [
                    _link(identifier, document.path.name),
                    _table_cell(metadata.get("title")),
                    _table_cell(metadata.get("status")),
                    _table_cell(metadata.get("date")),
                    _table_cell(metadata.get("scope")),
                ]
            )
            + " |"
        )
    if not repository.decisions:
        lines.append("| — | No Decision Records | — | — | — |")
    return "\n".join(lines).rstrip() + "\n"


def _change_entries(repository: KnowledgeRepository) -> list[tuple[str, str, str, str, str]]:
    entries: list[tuple[str, str, str, str, str]] = []
    for document in repository.changes:
        date = _string(document.metadata.get("date"))
        for change in document.metadata.get("changes", []):
            if not isinstance(change, dict):
                continue
            entries.append(
                (
                    _string(change.get("id")),
                    _string(change.get("target")),
                    _string(change.get("operation")),
                    date,
                    repository.relative(document.path),
                )
            )
    return sorted(entries)


def generate_change_index(repository: KnowledgeRepository) -> str:
    lines = _header("Semantic Change Index", "KnowledgeSystem/Tools/build-index")
    lines.extend(["| Change | Target | Operation | Date |", "| --- | --- | --- | --- |"])
    entries = _change_entries(repository)
    for identifier, target, operation, date, source_path in entries:
        relative_target = Path(source_path).relative_to("KnowledgeSystem/Changes").as_posix()
        lines.append(
            f"| {_link(identifier, relative_target + '#' + identifier.lower())} | "
            f"{_table_cell(target)} | {_table_cell(operation)} | {_table_cell(date)} |"
        )
    if not entries:
        lines.append("| — | No semantic changes | — | — |")
    return "\n".join(lines).rstrip() + "\n"


def generate_indexes(repository: KnowledgeRepository) -> list[GeneratedFile]:
    return [
        GeneratedFile(
            repository.system_root / "Knowledge" / "index.md",
            generate_knowledge_index(repository),
            repository.root,
        ),
        GeneratedFile(
            repository.system_root / "Decisions" / "index.md",
            generate_decision_index(repository),
            repository.root,
        ),
        GeneratedFile(
            repository.system_root / "Changes" / "index.md",
            generate_change_index(repository),
            repository.root,
        ),
    ]


def _knowledge_table(
    repository: KnowledgeRepository,
    *,
    title: str,
    predicate: Callable[[dict[str, object]], bool],
    empty: str,
) -> str:
    lines = _header(title, "KnowledgeSystem/Tools/build-views")
    lines.extend(["| ID | Claim | Topic | State | Maturity |", "| --- | --- | --- | --- | --- |"])
    selected = [document for document in repository.knowledge if predicate(document.metadata)]
    for document in sorted(selected, key=lambda item: str(item.metadata.get("id", ""))):
        metadata = document.metadata
        identifier = _string(metadata.get("id"))
        lines.append(
            "| "
            + " | ".join(
                [
                    _link(identifier, f"../Knowledge/items/{document.path.name}"),
                    _table_cell(metadata.get("summary")),
                    _table_cell(metadata.get("topic")),
                    _table_cell(metadata.get("state")),
                    _table_cell(metadata.get("maturity")),
                ]
            )
            + " |"
        )
    if not selected:
        lines.append(f"| — | {empty} | — | — | — |")
    return "\n".join(lines).rstrip() + "\n"


def generate_open_questions(repository: KnowledgeRepository) -> str:
    return _knowledge_table(
        repository,
        title="Open Questions",
        predicate=lambda item: item.get("kind") == "question" and item.get("state") == "active",
        empty="No open questions",
    )


def generate_decisions_required(repository: KnowledgeRepository) -> str:
    return _knowledge_table(
        repository,
        title="Decisions Required",
        predicate=lambda item: item.get("decision_required") is True and item.get("state") == "active",
        empty="No active Knowledge Objects are marked as requiring a decision",
    )


def generate_knowledge_map(repository: KnowledgeRepository) -> str:
    lines = _header("Knowledge Map", "KnowledgeSystem/Tools/build-views")
    by_topic: dict[str, list] = {}
    for document in repository.knowledge:
        topic = _string(document.metadata.get("topic")) or "unclassified"
        by_topic.setdefault(topic, []).append(document)
    for topic in sorted(by_topic):
        lines.extend([f"## {topic}", ""])
        for document in sorted(by_topic[topic], key=lambda item: str(item.metadata.get("id", ""))):
            metadata = document.metadata
            identifier = _string(metadata.get("id"))
            descriptor = f"{_string(metadata.get('kind'))}; {_string(metadata.get('state'))}; {_string(metadata.get('maturity'))}"
            lines.append(f"- {_link(identifier, '../Knowledge/items/' + document.path.name)} — {_string(metadata.get('title'))} ({descriptor})")
            relations = [
                relation
                for relation in metadata.get("relations", [])
                if isinstance(relation, dict) and isinstance(relation.get("target"), str)
            ]
            for relation in sorted(relations, key=lambda item: (str(item.get("type")), str(item.get("target")))):
                lines.append(f"  - `{_string(relation.get('type'))}` → `{_string(relation.get('target'))}`")
        lines.append("")
    if not by_topic:
        lines.append("No Knowledge Objects are registered.\n")
    return "\n".join(lines).rstrip() + "\n"


def generate_backlinks(repository: KnowledgeRepository) -> str:
    lines = _header("Backlinks", "KnowledgeSystem/Tools/build-views")
    links = collect_backlinks(repository)
    grouped: dict[str, list] = {}
    for link in links:
        grouped.setdefault(link.target, []).append(link)
    for target in sorted(grouped):
        lines.extend([f"## `{target}`", ""])
        for link in grouped[target]:
            lines.append(
                f"- `{link.source}` via `{link.relation}` ({link.edge_type}; `{link.source_path}`)"
            )
        lines.append("")
    if not grouped:
        lines.append("No backlinks are registered.\n")
    return "\n".join(lines).rstrip() + "\n"


def _topic_for(repository: KnowledgeRepository, slug: str, language: str):
    identifier = f"topic:{slug}"
    matches = [
        topic
        for topic in repository.topics
        if topic.metadata.get("id") == identifier and topic.metadata.get("language") == language
    ]
    if len(matches) != 1:
        raise KnowledgeError(
            f"Template requires exactly one {language} Topic '{identifier}', found {len(matches)}"
        )
    return matches[0]


def render_publication_template(
    repository: KnowledgeRepository,
    template_path: Path,
) -> str:
    """Render the intentionally small publication-template language."""

    template = template_path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    language = "de" if template_path.name.endswith(".de.template.md") else "en"
    output: list[str] = []
    for raw_line in template.splitlines(keepends=True):
        line = raw_line.rstrip("\n")
        include = INCLUDE_TOPIC_PATTERN.fullmatch(line)
        if include is not None:
            slug, section = include.groups()
            topic = _topic_for(repository, slug, language)
            output.append(extract_section_to_eof(topic.body, section))
            continue

        def replace_publication(match: re.Match[str]) -> str:
            field = match.group(1)
            if field not in repository.publication:
                raise KnowledgeError(f"Unknown publication field '{field}' in {repository.relative(template_path)}")
            value = repository.publication[field]
            if isinstance(value, (dict, list)):
                raise KnowledgeError(f"Publication field '{field}' must be a scalar")
            return _string(value)

        output.append(PUBLICATION_PATTERN.sub(replace_publication, raw_line))

    rendered = "".join(output)
    unresolved = UNRESOLVED_PATTERN.search(rendered)
    if unresolved is not None or "{{" in rendered or "}}" in rendered:
        position = unresolved.start() if unresolved is not None else min(
            value for value in (rendered.find("{{"), rendered.find("}}")) if value >= 0
        )
        fragment = rendered[position : position + 120].splitlines()[0]
        raise KnowledgeError(
            f"Unresolved or multiline template directive in "
            f"{repository.relative(template_path)} near {fragment!r}"
        )
    if GENERATED_COMMENT not in rendered and "Do not edit it directly." not in rendered:
        if rendered.startswith("---\n"):
            closing = rendered.find("\n---\n", 4)
            if closing == -1:
                raise KnowledgeError(f"Template frontmatter is not closed: {repository.relative(template_path)}")
            insert_at = closing + len("\n---\n")
            rendered = rendered[:insert_at] + "\n" + GENERATED_COMMENT + "\n" + rendered[insert_at:]
        else:
            rendered = GENERATED_COMMENT + "\n\n" + rendered
    return rendered.rstrip() + "\n"


def generate_views(repository: KnowledgeRepository) -> list[GeneratedFile]:
    outputs = [
        GeneratedFile(
            repository.system_root / "Views" / "open-questions.md",
            generate_open_questions(repository),
            repository.root,
        ),
        GeneratedFile(
            repository.system_root / "Views" / "decisions-required.md",
            generate_decisions_required(repository),
            repository.root,
        ),
        GeneratedFile(
            repository.system_root / "Views" / "knowledge-map.md",
            generate_knowledge_map(repository),
            repository.root,
        ),
        GeneratedFile(
            repository.system_root / "Views" / "backlinks.md",
            generate_backlinks(repository),
            repository.root,
        ),
    ]
    templates = [
        (repository.system_root / "Views" / "current-state.template.md", repository.root / "MeetingMinutes" / "current-state.md"),
        (repository.system_root / "Views" / "current-state.de.template.md", repository.root / "MeetingMinutes" / "current-state.de.md"),
    ]
    for template, target in templates:
        if not template.is_file():
            raise KnowledgeError(f"Missing publication template: {repository.relative(template)}")
        outputs.append(
            GeneratedFile(target, render_publication_template(repository, template), repository.root)
        )
    return outputs


def validate_generated_target(generated: GeneratedFile) -> None:
    """Reject generated targets that could write outside the repository."""

    if generated.repository_root is None:
        raise KnowledgeError(f"Generated output has no repository root: {generated.path}")
    root = generated.repository_root.resolve()
    target = generated.path
    if target.is_symlink():
        raise KnowledgeError(f"Generated output target must not be a symlink: {target}")
    resolved = target.resolve(strict=False)
    try:
        resolved.relative_to(root)
    except ValueError as error:
        raise KnowledgeError(f"Generated output target escapes repository root: {target}") from error


def generated_is_current(generated: GeneratedFile) -> bool:
    validate_generated_target(generated)
    return generated.path.is_file() and generated.path.read_text(encoding="utf-8") == generated.content


def apply_generated_files(files: list[GeneratedFile], *, check: bool) -> list[str]:
    """Write outputs, or return mismatches without mutating in check mode."""

    mismatches: list[str] = []
    for generated in files:
        if generated_is_current(generated):
            continue
        if check:
            mismatches.append(str(generated.path))
            continue
        generated.path.parent.mkdir(parents=True, exist_ok=True)
        validate_generated_target(generated)
        generated.path.write_text(generated.content, encoding="utf-8", newline="\n")
    return mismatches


def require_generated_match(files: list[GeneratedFile]) -> None:
    mismatches = apply_generated_files(files, check=True)
    if mismatches:
        raise BuildMismatchError("Generated files are stale: " + ", ".join(mismatches))
